// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3sTIHz3SaD3AOFXDfLgWc6b8CiFgKMk',
    appId: '1:174677721847:web:ca52d2a8c999e550a249f2',
    messagingSenderId: '174677721847',
    projectId: 'gestor-matriculas',
    authDomain: 'gestor-matriculas.firebaseapp.com',
    storageBucket: 'gestor-matriculas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXnnat0LsGEEhDi28968cnKNSFMoLtJE',
    appId: '1:174677721847:android:00ea1cbe05212531a249f2',
    messagingSenderId: '174677721847',
    projectId: 'gestor-matriculas',
    storageBucket: 'gestor-matriculas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCZE41Wku9EHv-qpbjTSmWll75OIaono',
    appId: '1:174677721847:ios:7be801d58dd41724a249f2',
    messagingSenderId: '174677721847',
    projectId: 'gestor-matriculas',
    storageBucket: 'gestor-matriculas.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );
}
